### ISSUE TITLE
Data availability?

### ISSUE THREAD

**Issue by rargelaguet** [sajuukLyu/CR_2023#1]
Hello,
congratulations on your [recent chemical reprogramming publication](https://pubmed.ncbi.nlm.nih.gov/37224020/), it's fascinating work! I am interested in exploring the 10x Multiome experiment, but I noticed that the [GEO data](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE213711) is still private. Are you going to make it publicly available some time soon?

Thank you,
Ricard Argelaguet

**Comment by sajuukLyu** [comment]
Thanks for your reminder, these data are publicly available now.

Yulin Lyu

**Comment by rargelaguet** [comment]
Hi Yulin,
thank you! I can see the GEO entries now and can download the supplementary .tar.gz files, but I still can't access the sequencing data from [SRA](https://www.ncbi.nlm.nih.gov/sra?term=SRX17630548). I get the error: "SRA Experiment SRX17630548 is not public". Could you please check? Thanks again.

**Comment by sajuukLyu** [comment]
Well, I met the same error and can't access the SRA data, either. Maybe there is a delay for SRA and GEO......

**Comment by rargelaguet** [comment]
yes probably, I'll check again in a couple of days. Thanks!
